const jwt = require('jsonwebtoken');
const crypto = require('crypto');
const asyncHandler = require('../utils/asyncHandler');
const User = require('../models/User');
const sendEmail = require('../utils/sendEmail');
const {
  assertStrongPassword,
  generateTemporaryPassword,
  PASSWORD_POLICY_MESSAGE,
} = require('../utils/passwordPolicy');

const getWebDashboardUrl = () =>
  (process.env.WEB_DASHBOARD_URL || 'http://localhost:5173').replace(/\/+$/, '');

// Generate JWT Token
const generateToken = (id) => {
  return jwt.sign({ id }, process.env.JWT_SECRET, {
    expiresIn: '30d',
  });
};

const buildAuthResponse = (user) => ({
  _id: user.id,
  name: user.name,
  email: user.email,
  role: user.role,
  mustChangePassword: Boolean(user.mustChangePassword),
  token: generateToken(user._id),
});

// @desc    Register a new user
// @route   POST /api/auth/register
// @access  Public
exports.registerUser = asyncHandler(async (req, res) => {
  const { name, email, registrationNumber, department } = req.body;
  let { password, role } = req.body;

  if (!name || !email) {
    res.status(400);
    throw new Error('Please add all basic fields');
  }

  // Role restriction: only admins can assign non-student roles
  if (role && role !== 'student') {
    if (!req.user || req.user.role !== 'admin') {
      res.status(403);
      throw new Error('Only admins can create non-student accounts');
    }
  } else {
    role = 'student';
  }

  if (role === 'student' && !registrationNumber) {
    res.status(400);
    throw new Error('Registration number is required for student accounts');
  }

  // Check if user exists
  const userExists = await User.findOne({ email });

  if (userExists) {
    res.status(400);
    throw new Error('User already exists');
  }

  // Auto-generate password if not provided
  let autoGeneratedPassword = null;
  if (!password) {
    autoGeneratedPassword = generateTemporaryPassword();
    password = autoGeneratedPassword;
  } else {
    res.status(400);
    assertStrongPassword(password);
  }

  // Create user
  const user = await User.create({
    name,
    email,
    password,
    role,
    registrationNumber: role === 'student' ? registrationNumber : undefined,
    department,
    mustChangePassword: Boolean(autoGeneratedPassword),
  });

  if (user) {
    // If we auto-generated a password, send the welcome email!
    if (autoGeneratedPassword) {
      const message = `Welcome to KaziLog!\n\nYour account has been created by the System Administrator. You can now log into your dashboard.\n\nYour Temporary Password is: ${autoGeneratedPassword}\n\nYou must change this password the first time you sign in.\n\nPassword requirements: ${PASSWORD_POLICY_MESSAGE}`;
      
      try {
        await sendEmail({
          email: user.email,
          subject: 'KaziLog - Your Account Details',
          message
        });
      } catch (err) {
        console.error('Error sending welcome email:', err);
      }
    }

    res.status(201).json(buildAuthResponse(user));
  } else {
    res.status(400);
    throw new Error('Invalid user data');
  }
});

// @desc    Authenticate a user
// @route   POST /api/auth/login
// @access  Public
exports.loginUser = asyncHandler(async (req, res) => {
  const { email, password } = req.body;

  // Check for user email
  const user = await User.findOne({ email }).select('+password');

  if (user && (await user.matchPassword(password))) {
    res.json(buildAuthResponse(user));
  } else {
    res.status(401);
    throw new Error('Invalid credentials');
  }
});

// @desc    Get user data
// @route   GET /api/auth/me
// @access  Private
exports.getMe = asyncHandler(async (req, res) => {
  res.status(200).json(req.user);
});

// @desc    Change password for authenticated user
// @route   PUT /api/auth/change-password
// @access  Private
exports.changePassword = asyncHandler(async (req, res) => {
  const { currentPassword, newPassword } = req.body;

  if (!currentPassword || !newPassword) {
    res.status(400);
    throw new Error('Current password and new password are required');
  }

  res.status(400);
  assertStrongPassword(newPassword);

  const user = await User.findById(req.user._id).select('+password');

  if (!user || !(await user.matchPassword(currentPassword))) {
    res.status(401);
    throw new Error('Current password is incorrect');
  }

  if (await user.matchPassword(newPassword)) {
    res.status(400);
    throw new Error('New password must be different from the current password');
  }

  user.password = newPassword;
  user.mustChangePassword = false;
  await user.save();

  res.status(200).json(buildAuthResponse(user));
});

// @desc    Forgot Password
// @route   POST /api/auth/forgotpassword
// @access  Public
exports.forgotPassword = asyncHandler(async (req, res) => {
  const user = await User.findOne({ email: req.body.email });

  if (!user) {
    res.status(404);
    throw new Error('There is no user with that email');
  }

  // Get reset token
  const resetToken = user.getResetPasswordToken();
  await user.save({ validateBeforeSave: false });

  // Create reset url
  const resetUrl = `${getWebDashboardUrl()}/reset-password/${resetToken}`;

  const message = `You are receiving this email because you (or someone else) has requested the reset of a password.\n\nPlease click on the following link to reset your password: \n\n ${resetUrl}`;

  try {
    await sendEmail({
      email: user.email,
      subject: 'KaziLog - Password Reset Token',
      message
    });

    res.status(200).json({ success: true, data: 'Email sent' });
  } catch (err) {
    console.error(err);
    user.resetPasswordToken = undefined;
    user.resetPasswordExpire = undefined;
    await user.save({ validateBeforeSave: false });
    res.status(500);
    throw new Error('Email could not be sent');
  }
});

// @desc    Reset Password
// @route   PUT /api/auth/resetpassword/:resettoken
// @access  Public
exports.resetPassword = asyncHandler(async (req, res) => {
  // Get hashed token
  const resetPasswordToken = crypto.createHash('sha256').update(req.params.resettoken).digest('hex');

  const user = await User.findOne({
    resetPasswordToken,
    resetPasswordExpire: { $gt: Date.now() }
  });

  if (!user) {
    res.status(400);
    throw new Error('Invalid or expired token');
  }

  res.status(400);
  assertStrongPassword(req.body.password);

  // Set new password
  user.password = req.body.password;
  user.mustChangePassword = false;
  user.resetPasswordToken = undefined;
  user.resetPasswordExpire = undefined;
  await user.save();

  res.status(200).json({
    success: true,
    ...buildAuthResponse(user),
  });
});
